{
  "fr": {
    "schaal.1": "Jamais",
    "schaal.2": "Rarement",
    "schaal.3": "Parfois",
    "schaal.4": "Souvent",
    "schaal.5": "Toujours",
    "A.naam": "Fondement — Adéquation des valeurs et des normes",
    "A.instructie": "Indiquez dans quelle mesure chaque affirmation s'applique à votre équipe.",
    "F1": "Ce que nous trouvons important dans notre travail au sein de cette équipe (qualité, engagement, rapport aux erreurs) correspond étroitement.",
    "F2": "Nous partageons les mêmes conceptions de ce qui constitue un comportement professionnel acceptable et de ce qui ne l'est pas.",
    "F3": "Nous avons une vision partagée de ce que représente cette équipe et de la raison de son existence.",
    "F4": "Nos valeurs personnelles (honnêteté, respect, fiabilité) s'accordent bien les unes avec les autres.",
    "F5": "Je me sens à l'aise avec la façon dont nous interagissons au sein de cette équipe.",
    "F6": "Nous avons les mêmes attentes quant à la manière dont nous gérons les engagements et les responsabilités.",
    "F7": "Lorsqu'il existe une divergence de valeurs ou de normes, nous sommes capables de la nommer et de la clarifier.",
    "F8": "Je me reconnais dans les 'règles non écrites' partagées de cette équipe.",
    "B.naam": "Fonctionnement de l'équipe",
    "B.instructie": "Indiquez dans quelle mesure chaque affirmation s'applique à votre équipe. Répondez en vous fiant à votre première impression.",
    "L1": "Les membres de l'équipe reconnaissent leurs erreurs.",
    "L2": "Les membres de l'équipe s'expriment avec passion et ouverture lors des discussions.",
    "L3": "Les membres de l'équipe soulignent rapidement les contributions et les réalisations des autres.",
    "L4": "Les réunions d'équipe sont intéressantes et engageantes (pas ennuyeuses).",
    "L5": "Lors des réunions, les questions les plus importantes — et les plus difficiles — sont abordées.",
    "L6": "Les membres de l'équipe reconnaissent leurs faiblesses les uns envers les autres.",
    "L7": "Les membres de l'équipe expriment leur opinion, même au risque de provoquer des désaccords.",
    "L8": "Les membres de l'équipe soulignent les comportements non productifs des autres.",
    "L9": "L'équipe a la réputation d'être très performante.",
    "L10": "Les membres de l'équipe demandent de l'aide sans hésiter.",
    "L11": "Les membres de l'équipe quittent les réunions avec la conviction que chacun s'engage à respecter les décisions prises.",
    "L12": "Lors des discussions, les membres de l'équipe se challengent mutuellement sur la manière dont ils sont parvenus à leurs conclusions et opinions.",
    "L13": "Les membres de l'équipe sollicitent l'avis des autres sur leurs domaines de responsabilité.",
    "L14": "Lorsque l'équipe n'atteint pas ses objectifs collectifs, chaque membre assume une responsabilité personnelle pour améliorer la performance de l'équipe.",
    "L15": "Les membres de l'équipe acceptent volontiers des sacrifices dans leur propre domaine dans l'intérêt général de l'équipe.",
    "L16": "Les membres de l'équipe confrontent rapidement les autres sur les problèmes relevant de leurs domaines de responsabilité respectifs.",
    "L17": "Les membres de l'équipe reconnaissent et exploitent les compétences et l'expertise des autres.",
    "L18": "Les membres de l'équipe se demandent mutuellement leur avis lors des réunions.",
    "L19": "Les membres de l'équipe concluent les discussions par des décisions et des actions claires et spécifiques.",
    "L20": "Les membres de l'équipe se remettent mutuellement en question sur leurs approches et méthodes de travail actuelles.",
    "L21": "L'équipe veille à ce que les membres peu performants ressentent une pression et une attente d'amélioration.",
    "L22": "Les membres de l'équipe s'excusent volontiers les uns envers les autres.",
    "L23": "Les membres de l'équipe communiquent des opinions impopulaires au groupe.",
    "L24": "L'équipe a une vision claire de sa direction et de ses priorités.",
    "L25": "Les membres de l'équipe hésitent à s'attribuer le mérite de leurs propres contributions.",
    "L26": "Tous les membres de l'équipe sont tenus aux mêmes normes élevées.",
    "L27": "Lorsqu'un conflit survient, l'équipe l'aborde et le résout avant de passer à un autre sujet.",
    "L28": "L'équipe est alignée autour d'objectifs communs.",
    "L29": "L'équipe atteint régulièrement ses objectifs.",
    "L30": "L'équipe prend des décisions rapidement, même lorsque toutes les informations ne sont pas disponibles.",
    "L31": "Les membres de l'équipe valorisent davantage le succès collectif que la performance individuelle.",
    "L32": "Les membres de l'équipe font preuve d'ouverture et de sincérité les uns envers les autres.",
    "L33": "Les membres de l'équipe peuvent parler confortablement de leur vie privée entre eux.",
    "L34": "L'équipe respecte les décisions prises.",
    "L35": "Les membres de l'équipe tiennent systématiquement leurs promesses et engagements.",
    "L36": "Les membres de l'équipe se donnent mutuellement des retours constructifs sans y être invités.",
    "L37": "Les membres de l'équipe accordent peu d'importance aux titres et au statut.",
    "L38": "Les membres de l'équipe soutiennent les décisions du groupe, même s'ils n'étaient pas d'accord au départ.",
    "C.naam": "Anatomie de la confiance",
    "C.instructie": "La confiance est constituée de cinq éléments. Classez-les d'abord du plus important (1) au moins important (5) — chaque chiffre ne peut apparaître qu'une seule fois. Indiquez ensuite pour chaque élément à quel point votre équipe y performe aujourd'hui.",
    "C.intentie.naam": "Intention",
    "C.intentie.omschrijving": "Je crois que mes coéquipiers ont de bonnes intentions envers moi.",
    "C.competentie.naam": "Compétence",
    "C.competentie.omschrijving": "Je fais confiance à mes coéquipiers pour bien accomplir leur travail.",
    "C.caring.naam": "Caring",
    "C.caring.omschrijving": "Je sens que mes coéquipiers se soucient de moi et des autres.",
    "C.transparantie.naam": "Transparence",
    "C.transparantie.omschrijving": "Mes coéquipiers sont ouverts et honnêtes sur ce qu'ils pensent et font.",
    "C.gealigneerd.naam": "Aligné sur l'objectif",
    "C.gealigneerd.omschrijving": "Je fais confiance au fait que nous travaillons tous vers le même objectif.",
    "C.prestatie.1": "Très faible",
    "C.prestatie.2": "Faible",
    "C.prestatie.3": "Moyen",
    "C.prestatie.4": "Fort",
    "C.prestatie.5": "Très fort",
    "pijler.fundament.naam": "Fondement — Adéquation des valeurs et des normes",
    "pijler.fundament.korteUitleg": "La mesure dans laquelle les membres de l'équipe s'accordent sur les valeurs et normes professionnelles et personnelles — le terreau dans lequel la confiance peut s'enraciner.",
    "pijler.vertrouwen.naam": "Confiance",
    "pijler.vertrouwen.korteUitleg": "Confiance basée sur la vulnérabilité : les membres de l'équipe osent se montrer vulnérables, admettre leurs erreurs et demander de l'aide.",
    "pijler.conflict.naam": "Conflit",
    "pijler.conflict.korteUitleg": "Conflit d'idées productif : l'équipe mène des débats ouverts et passionnés sur les idées sans devenir destructive.",
    "pijler.betrokkenheid.naam": "Engagement",
    "pijler.betrokkenheid.korteUitleg": "Commitment : l'équipe prend des décisions claires et chacun les soutient, même en cas de désaccord.",
    "pijler.verantwoordelijkheid.naam": "Responsabilité",
    "pijler.verantwoordelijkheid.korteUitleg": "Responsabilisation mutuelle : les membres de l'équipe se tiennent mutuellement responsables des comportements et performances susceptibles de nuire à l'équipe.",
    "pijler.resultaten.naam": "Résultats",
    "pijler.resultaten.korteUitleg": "Focus sur les résultats collectifs : l'équipe place les objectifs d'équipe au-dessus du statut et de l'ego individuels."
  },
  "en": {
    "schaal.1": "Never",
    "schaal.2": "Rarely",
    "schaal.3": "Sometimes",
    "schaal.4": "Often",
    "schaal.5": "Always",
    "A.naam": "Foundation — Values & Norms Fit",
    "A.instructie": "Indicate to what extent each statement applies to your team.",
    "F1": "What we consider important in our work on this team (quality, commitment, handling mistakes) aligns closely.",
    "F2": "We share the same views on what constitutes professionally acceptable behavior and what does not.",
    "F3": "We have a shared picture of what this team stands for and why it exists.",
    "F4": "Our personal values (honesty, respect, reliability) are well aligned with one another.",
    "F5": "I feel at home with the way we interact with each other on this team.",
    "F6": "We have the same expectations about how we manage commitments and responsibilities.",
    "F7": "When there is a difference in values or norms, we are able to name it and work it out.",
    "F8": "I recognize myself in the shared 'unwritten rules' of this team.",
    "B.naam": "Team Functioning",
    "B.instructie": "Indicate to what extent each statement applies to your team. Answer based on your first impression.",
    "L1": "Team members admit their mistakes.",
    "L2": "Team members are passionate and open in discussing issues.",
    "L3": "Team members quickly acknowledge the contributions and accomplishments of others.",
    "L4": "Team meetings are interesting and engaging (not boring).",
    "L5": "During meetings, the most important — and most difficult — issues are discussed.",
    "L6": "Team members acknowledge their weaknesses to one another.",
    "L7": "Team members express their opinions, even at the risk of disagreement.",
    "L8": "Team members call out each other's unproductive behavior.",
    "L9": "The team has a reputation for high performance.",
    "L10": "Team members ask for help without hesitation.",
    "L11": "Team members leave meetings confident that everyone is committed to the decisions made.",
    "L12": "During discussions, team members challenge each other on how they arrived at their conclusions and opinions.",
    "L13": "Team members ask one another for input on their areas of responsibility.",
    "L14": "When the team fails to meet its collective goals, each member takes personal responsibility to improve team performance.",
    "L15": "Team members willingly make sacrifices in their own domain for the overall good of the team.",
    "L16": "Team members quickly confront each other about problems in their respective areas of responsibility.",
    "L17": "Team members recognize and leverage each other's skills and expertise.",
    "L18": "Team members ask each other for their opinions during meetings.",
    "L19": "Team members end discussions with clear and specific decisions and action items.",
    "L20": "Team members question each other about their current approaches and working methods.",
    "L21": "The team ensures that low performers feel pressure and an expectation to improve.",
    "L22": "Team members willingly apologize to one another.",
    "L23": "Team members communicate unpopular opinions to the group.",
    "L24": "The team has a clear picture of its direction and priorities.",
    "L25": "Team members are reluctant to claim credit for their own contributions.",
    "L26": "All team members are held to the same high standards.",
    "L27": "When conflict arises, the team addresses and resolves the issue before moving on to another topic.",
    "L28": "The team is aligned around common goals.",
    "L29": "The team consistently meets its goals.",
    "L30": "The team is decisive, even when not all information is available.",
    "L31": "Team members value collective success more than individual achievement.",
    "L32": "Team members are open and candid with one another.",
    "L33": "Team members can comfortably talk about their personal lives with each other.",
    "L34": "The team stands by decisions once made.",
    "L35": "Team members consistently follow through on their commitments and agreements.",
    "L36": "Team members give each other constructive feedback without being asked.",
    "L37": "Team members attach little importance to titles and status.",
    "L38": "Team members support group decisions, even if they initially disagreed.",
    "C.naam": "Trust Anatomy",
    "C.instructie": "Trust is built from five elements. First, rank them from most important (1) to least important (5) — each number may only be used once. Then indicate how strongly your team performs on each element today.",
    "C.intentie.naam": "Intention",
    "C.intentie.omschrijving": "I believe that my team members have my best interests at heart.",
    "C.competentie.naam": "Competence",
    "C.competentie.omschrijving": "I trust that my team members can do their work well.",
    "C.caring.naam": "Caring",
    "C.caring.omschrijving": "I feel that my team members care about me and about others.",
    "C.transparantie.naam": "Transparency",
    "C.transparantie.omschrijving": "My team members are open and honest about what they think and do.",
    "C.gealigneerd.naam": "Aligned on Purpose",
    "C.gealigneerd.omschrijving": "I trust that we are all working toward the same goal.",
    "C.prestatie.1": "Very weak",
    "C.prestatie.2": "Weak",
    "C.prestatie.3": "Moderate",
    "C.prestatie.4": "Strong",
    "C.prestatie.5": "Very strong",
    "pijler.fundament.naam": "Foundation — Values & Norms Fit",
    "pijler.fundament.korteUitleg": "The degree to which team members are aligned on professional and personal values and norms — the soil in which trust can take root.",
    "pijler.vertrouwen.naam": "Trust",
    "pijler.vertrouwen.korteUitleg": "Vulnerability-based trust: team members dare to be vulnerable, admit mistakes, and ask for help.",
    "pijler.conflict.naam": "Conflict",
    "pijler.conflict.korteUitleg": "Productive ideological conflict: the team engages in open, passionate debates about ideas without becoming destructive.",
    "pijler.betrokkenheid.naam": "Commitment",
    "pijler.betrokkenheid.korteUitleg": "Commitment: the team makes clear decisions and everyone rallies behind them, even in the face of disagreement.",
    "pijler.verantwoordelijkheid.naam": "Accountability",
    "pijler.verantwoordelijkheid.korteUitleg": "Mutual accountability: team members hold each other accountable for behaviors and performance that may harm the team.",
    "pijler.resultaten.naam": "Results",
    "pijler.resultaten.korteUitleg": "Focus on collective results: the team places team goals above individual status and ego."
  },
  "es": {
    "schaal.1": "Nunca",
    "schaal.2": "Raramente",
    "schaal.3": "A veces",
    "schaal.4": "Con frecuencia",
    "schaal.5": "Siempre",
    "A.naam": "Fundamento — Ajuste de valores y normas",
    "A.instructie": "Indique en qué medida cada afirmación se aplica a su equipo.",
    "F1": "Lo que consideramos importante en nuestro trabajo dentro de este equipo (calidad, compromiso, manejo de errores) coincide en gran medida.",
    "F2": "Compartimos las mismas concepciones sobre qué comportamiento profesional es aceptable y cuál no lo es.",
    "F3": "Tenemos una visión compartida de lo que representa este equipo y por qué existe.",
    "F4": "Nuestros valores personales (honestidad, respeto, fiabilidad) se alinean bien entre sí.",
    "F5": "Me siento cómodo con la forma en que nos relacionamos dentro de este equipo.",
    "F6": "Tenemos las mismas expectativas sobre cómo gestionamos los compromisos y las responsabilidades.",
    "F7": "Cuando existe una diferencia de valores o normas, somos capaces de nombrarla y aclararla.",
    "F8": "Me identifico con las 'reglas no escritas' compartidas de este equipo.",
    "B.naam": "Funcionamiento del equipo",
    "B.instructie": "Indique en qué medida cada afirmación se aplica a su equipo. Responda basándose en su primera impresión.",
    "L1": "Los miembros del equipo admiten sus errores.",
    "L2": "Los miembros del equipo son apasionados y abiertos en las discusiones.",
    "L3": "Los miembros del equipo reconocen rápidamente las contribuciones y logros de los demás.",
    "L4": "Las reuniones del equipo son interesantes y dinámicas (no aburridas).",
    "L5": "Durante las reuniones se abordan los asuntos más importantes — y más difíciles.",
    "L6": "Los miembros del equipo reconocen sus debilidades mutuamente.",
    "L7": "Los miembros del equipo expresan su opinión, incluso a riesgo de generar desacuerdo.",
    "L8": "Los miembros del equipo señalan los comportamientos no productivos de los demás.",
    "L9": "El equipo tiene reputación de alto rendimiento.",
    "L10": "Los miembros del equipo piden ayuda sin dudar.",
    "L11": "Los miembros del equipo salen de las reuniones con la confianza de que todos se comprometen con los acuerdos alcanzados.",
    "L12": "Durante las discusiones, los miembros del equipo se desafían mutuamente sobre cómo llegaron a sus conclusiones y opiniones.",
    "L13": "Los miembros del equipo solicitan aportaciones de los demás sobre sus áreas de responsabilidad.",
    "L14": "Cuando el equipo no alcanza sus objetivos colectivos, cada miembro asume responsabilidad personal para mejorar el rendimiento del equipo.",
    "L15": "Los miembros del equipo aceptan de buen grado sacrificar en su propio ámbito en beneficio del interés general del equipo.",
    "L16": "Los miembros del equipo confrontan rápidamente a los demás sobre problemas en sus respectivas áreas de responsabilidad.",
    "L17": "Los miembros del equipo reconocen y aprovechan las habilidades y la experiencia de los demás.",
    "L18": "Los miembros del equipo se piden mutuamente su opinión durante las reuniones.",
    "L19": "Los miembros del equipo concluyen las discusiones con decisiones y acciones claras y específicas.",
    "L20": "Los miembros del equipo se cuestionan mutuamente sobre sus enfoques y métodos de trabajo actuales.",
    "L21": "El equipo se asegura de que los miembros con bajo rendimiento sientan presión y expectativa de mejora.",
    "L22": "Los miembros del equipo se disculpan entre sí con disposición.",
    "L23": "Los miembros del equipo comunican opiniones impopulares al grupo.",
    "L24": "El equipo tiene una visión clara de su dirección y prioridades.",
    "L25": "Los miembros del equipo son reacios a atribuirse el mérito de sus propias contribuciones.",
    "L26": "Todos los miembros del equipo están sujetos a los mismos estándares elevados.",
    "L27": "Cuando surge un conflicto, el equipo lo aborda y resuelve antes de pasar a otro tema.",
    "L28": "El equipo está alineado en torno a objetivos comunes.",
    "L29": "El equipo alcanza sus objetivos de forma consistente.",
    "L30": "El equipo toma decisiones con determinación, incluso cuando no dispone de toda la información.",
    "L31": "Los miembros del equipo valoran el éxito colectivo más que el rendimiento individual.",
    "L32": "Los miembros del equipo son abiertos y sinceros entre sí.",
    "L33": "Los miembros del equipo pueden hablar con comodidad sobre su vida personal entre ellos.",
    "L34": "El equipo mantiene las decisiones una vez tomadas.",
    "L35": "Los miembros del equipo cumplen sistemáticamente sus promesas y compromisos.",
    "L36": "Los miembros del equipo se ofrecen mutuamente retroalimentación constructiva sin que se la pidan.",
    "L37": "Los miembros del equipo conceden poca importancia a los títulos y el estatus.",
    "L38": "Los miembros del equipo apoyan las decisiones del grupo, aunque inicialmente no estuvieran de acuerdo.",
    "C.naam": "Anatomía de la confianza",
    "C.instructie": "La confianza se construye a partir de cinco elementos. Primero, ordénelos del más importante (1) al menos importante (5) — cada número solo puede aparecer una vez. Luego indique con qué solidez rinde su equipo en cada elemento hoy.",
    "C.intentie.naam": "Intención",
    "C.intentie.omschrijving": "Creo que mis compañeros de equipo tienen buenas intenciones hacia mí.",
    "C.competentie.naam": "Competencia",
    "C.competentie.omschrijving": "Confío en que mis compañeros de equipo pueden hacer bien su trabajo.",
    "C.caring.naam": "Caring",
    "C.caring.omschrijving": "Siento que mis compañeros de equipo se preocupan por mí y por los demás.",
    "C.transparantie.naam": "Transparencia",
    "C.transparantie.omschrijving": "Mis compañeros de equipo son abiertos y honestos sobre lo que piensan y hacen.",
    "C.gealigneerd.naam": "Alineado con el propósito",
    "C.gealigneerd.omschrijving": "Confío en que todos estamos trabajando hacia el mismo objetivo.",
    "C.prestatie.1": "Muy débil",
    "C.prestatie.2": "Débil",
    "C.prestatie.3": "Moderado",
    "C.prestatie.4": "Fuerte",
    "C.prestatie.5": "Muy fuerte",
    "pijler.fundament.naam": "Fundamento — Ajuste de valores y normas",
    "pijler.fundament.korteUitleg": "El grado en que los miembros del equipo se alinean en valores y normas profesionales y personales — el terreno en el que la confianza puede arraigar.",
    "pijler.vertrouwen.naam": "Confianza",
    "pijler.vertrouwen.korteUitleg": "Confianza basada en la vulnerabilidad: los miembros del equipo se atreven a mostrarse vulnerables, admitir errores y pedir ayuda.",
    "pijler.conflict.naam": "Conflicto",
    "pijler.conflict.korteUitleg": "Conflicto de ideas productivo: el equipo mantiene debates abiertos y apasionados sobre ideas sin volverse destructivo.",
    "pijler.betrokkenheid.naam": "Compromiso",
    "pijler.betrokkenheid.korteUitleg": "Commitment: el equipo toma decisiones claras y todos las respaldan, incluso ante desacuerdos.",
    "pijler.verantwoordelijkheid.naam": "Responsabilidad",
    "pijler.verantwoordelijkheid.korteUitleg": "Responsabilidad mutua: los miembros del equipo se exigen mutuamente en cuanto a comportamientos y rendimiento que puedan perjudicar al equipo.",
    "pijler.resultaten.naam": "Resultados",
    "pijler.resultaten.korteUitleg": "Enfoque en los resultados colectivos: el equipo sitúa los objetivos del equipo por encima del estatus y el ego individuales."
  },
  "ru": {
    "schaal.1": "Никогда",
    "schaal.2": "Редко",
    "schaal.3": "Иногда",
    "schaal.4": "Часто",
    "schaal.5": "Всегда",
    "A.naam": "Фундамент — Соответствие ценностей и норм",
    "A.instructie": "Укажите, в какой мере каждое утверждение применимо к вашей команде.",
    "F1": "То, что мы считаем важным в нашей работе в этой команде (качество, вовлечённость, отношение к ошибкам), в значительной мере совпадает.",
    "F2": "Мы разделяем одинаковые представления о том, что является профессионально приемлемым поведением, а что нет.",
    "F3": "У нас есть общее представление о том, что олицетворяет эта команда и для чего она существует.",
    "F4": "Наши личные ценности (честность, уважение, надёжность) хорошо согласуются друг с другом.",
    "F5": "Я чувствую себя комфортно в той манере общения, которая принята в этой команде.",
    "F6": "У нас одинаковые ожидания относительно того, как мы выполняем договорённости и несём ответственность.",
    "F7": "Когда возникают расхождения в ценностях или нормах, мы способны их назвать и прояснить.",
    "F8": "Я узнаю себя в общих «неписаных правилах» этой команды.",
    "B.naam": "Функционирование команды",
    "B.instructie": "Укажите, в какой мере каждое утверждение применимо к вашей команде. Отвечайте на основе первого впечатления.",
    "L1": "Члены команды признают свои ошибки.",
    "L2": "Члены команды увлечённо и открыто участвуют в обсуждениях.",
    "L3": "Члены команды быстро отмечают вклад и достижения друг друга.",
    "L4": "Командные встречи интересны и содержательны (не скучны).",
    "L5": "На встречах обсуждаются наиболее важные — и наиболее сложные — вопросы.",
    "L6": "Члены команды признают свои слабые стороны друг перед другом.",
    "L7": "Члены команды высказывают своё мнение, даже рискуя вызвать разногласия.",
    "L8": "Члены команды указывают друг другу на непродуктивное поведение.",
    "L9": "Команда имеет репутацию высокой результативности.",
    "L10": "Члены команды обращаются за помощью без колебаний.",
    "L11": "Члены команды покидают встречи с уверенностью в том, что каждый готов выполнять принятые решения.",
    "L12": "В ходе дискуссий члены команды ставят под сомнение рассуждения друг друга, спрашивая, как те пришли к своим выводам и мнениям.",
    "L13": "Члены команды запрашивают мнение друг друга по своим областям ответственности.",
    "L14": "Когда команда не достигает коллективных целей, каждый член берёт на себя личную ответственность за улучшение результатов команды.",
    "L15": "Члены команды готовы идти на жертвы в своей области ради общего блага команды.",
    "L16": "Члены команды оперативно указывают друг другу на проблемы в соответствующих областях ответственности.",
    "L17": "Члены команды признают и используют навыки и экспертизу друг друга.",
    "L18": "Члены команды спрашивают мнение друг друга на встречах.",
    "L19": "Члены команды завершают обсуждения чёткими и конкретными решениями и пунктами действий.",
    "L20": "Члены команды задают друг другу вопросы об их текущих подходах и методах работы.",
    "L21": "Команда следит за тем, чтобы низкорезультативные сотрудники ощущали давление и ожидание улучшений.",
    "L22": "Члены команды охотно приносят извинения друг другу.",
    "L23": "Члены команды высказывают группе непопулярные мнения.",
    "L24": "У команды есть чёткое представление о направлении и приоритетах.",
    "L25": "Члены команды неохотно приписывают себе заслуги за собственный вклад.",
    "L26": "Все члены команды придерживаются одних и тех же высоких стандартов.",
    "L27": "Когда возникает конфликт, команда рассматривает и разрешает его, прежде чем переходить к другой теме.",
    "L28": "Команда согласована в отношении общих целей.",
    "L29": "Команда последовательно достигает своих целей.",
    "L30": "Команда принимает решения решительно, даже когда не вся информация доступна.",
    "L31": "Члены команды ценят коллективный успех выше индивидуальных достижений.",
    "L32": "Члены команды открыты и искренни друг с другом.",
    "L33": "Члены команды могут свободно говорить о своей личной жизни между собой.",
    "L34": "Команда придерживается принятых решений.",
    "L35": "Члены команды последовательно выполняют свои обещания и договорённости.",
    "L36": "Члены команды дают друг другу конструктивную обратную связь по собственной инициативе.",
    "L37": "Члены команды придают мало значения титулам и статусу.",
    "L38": "Члены команды поддерживают групповые решения, даже если изначально были с ними не согласны.",
    "C.naam": "Анатомия доверия",
    "C.instructie": "Доверие складывается из пяти элементов. Сначала расположите их по степени важности от наиболее важного (1) до наименее важного (5) — каждая цифра может использоваться только один раз. Затем укажите, насколько сильно ваша команда работает по каждому элементу сегодня.",
    "C.intentie.naam": "Намерение",
    "C.intentie.omschrijving": "Я верю, что мои коллеги по команде желают мне добра.",
    "C.competentie.naam": "Компетентность",
    "C.competentie.omschrijving": "Я доверяю тому, что мои коллеги способны хорошо выполнять свою работу.",
    "C.caring.naam": "Caring",
    "C.caring.omschrijving": "Я чувствую, что мои коллеги заботятся обо мне и о других.",
    "C.transparantie.naam": "Прозрачность",
    "C.transparantie.omschrijving": "Мои коллеги открыты и честны в отношении того, что они думают и делают.",
    "C.gealigneerd.naam": "Ориентированность на общую цель",
    "C.gealigneerd.omschrijving": "Я доверяю тому, что мы все работаем к одной и той же цели.",
    "C.prestatie.1": "Очень слабо",
    "C.prestatie.2": "Слабо",
    "C.prestatie.3": "Умеренно",
    "C.prestatie.4": "Сильно",
    "C.prestatie.5": "Очень сильно",
    "pijler.fundament.naam": "Фундамент — Соответствие ценностей и норм",
    "pijler.fundament.korteUitleg": "Степень, в которой члены команды согласованы по профессиональным и личным ценностям и нормам — почва, в которой может укорениться доверие.",
    "pijler.vertrouwen.naam": "Доверие",
    "pijler.vertrouwen.korteUitleg": "Доверие на основе уязвимости: члены команды решаются проявлять уязвимость, признавать ошибки и просить о помощи.",
    "pijler.conflict.naam": "Конфликт",
    "pijler.conflict.korteUitleg": "Продуктивный конфликт идей: команда ведёт открытые, страстные дискуссии об идеях, не переходя к деструктивному поведению.",
    "pijler.betrokkenheid.naam": "Вовлечённость",
    "pijler.betrokkenheid.korteUitleg": "Commitment: команда принимает чёткие решения, и все их поддерживают, даже при наличии разногласий.",
    "pijler.verantwoordelijkheid.naam": "Ответственность",
    "pijler.verantwoordelijkheid.korteUitleg": "Взаимная подотчётность: члены команды требуют друг от друга ответственности за поведение и результаты, которые могут навредить команде.",
    "pijler.resultaten.naam": "Результаты",
    "pijler.resultaten.korteUitleg": "Фокус на коллективных результатах: команда ставит командные цели выше индивидуального статуса и эго."
  }
}
